name: Continuous Delivery

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '22' ]
    name: verify using node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
      - run: npm run verify
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: coverage (node v${{ matrix.node }})
          path: coverage/

  publish:
    needs: verify
    runs-on: ubuntu-latest
    name: publish package if needed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
